# Setup
title: 'Faris Blog'
tagline: 'My Blog'
description: 'A blog to explain stuff ğŸ˜'
url: 'https://www.farisotaibi.com/blog'
baseurl: 'https://www.farisotaibi.com/blog'
paginate: 5
permalink: pretty

# About/contact
author:
  name: 'Faris AL-Otaibi'
  url: 'https://linktr.ee/farisc0de'
  email: 'farisksa79@gmail.com'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
